<a href="https://colab.research.google.com/github/IlyaMolchanovv/MachineLearning/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
x = np.random.randint(0,10,10)
i_non = np.nonzero(x)
print(x)
print(i_non)

[8 7 3 5 2 6 6 3 9 7]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)


In [10]:
mtrx = np.arange(9).reshape((3,3))
print(mtrx)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
b_pat = np.array([[0,1],[1,0]])
mtrx = np.tile(b_pat, (4,4))
print(mtrx)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [13]:
vect = np.random.rand(10)
print(f"{vect}\n")
min_val = np.min(vect)
min_ind = np.argmin(vect)
vect[min_ind] = 0
print(vect)

[0.19533789 0.75414981 0.93941021 0.6037796  0.91692111 0.81099929
 0.28098962 0.3831111  0.24048982 0.76018855]

[0.         0.75414981 0.93941021 0.6037796  0.91692111 0.81099929
 0.28098962 0.3831111  0.24048982 0.76018855]


In [15]:
vect = np.random.randint(0, 10, 100)
most_com_value = np.bincount(vect).argmax()
print(f"{vect}\n\n{most_com_value}")

[6 6 8 7 3 4 5 6 5 8 1 5 8 0 4 3 5 1 6 0 6 4 9 5 6 1 7 0 4 4 0 5 2 0 5 0 8
 8 4 2 3 7 0 3 6 8 9 2 0 6 5 8 7 0 2 2 3 0 2 7 2 3 9 5 4 3 8 0 3 9 9 8 0 3
 7 9 2 4 8 8 5 7 4 3 5 5 5 8 9 5 2 6 6 7 3 3 3 8 6 1]

5


In [16]:
mtrx = np.random.rand(3,3)
row_means = np.mean(mtrx, axis=1)
res = mtrx - row_means[:, np.newaxis]
print(f"{mtrx}\n\n{res}")

[[0.38525912 0.96510532 0.65534813]
 [0.90067911 0.62973306 0.17436132]
 [0.15375066 0.23910445 0.99540195]]

[[-0.28331174  0.29653446 -0.01322272]
 [ 0.33242128  0.06147523 -0.39389651]
 [-0.30900169 -0.22364791  0.5326496 ]]


In [17]:
mtrx = np.random.rand(3,3)
print(f"исходная:\n{mtrx}")
mtrx[[0,1]] = mtrx[[1,0]]
print(f"после замены:\n{mtrx}")

исходная:
[[0.13826518 0.18122257 0.1208711 ]
 [0.76165116 0.23164168 0.73585308]
 [0.53406227 0.64195642 0.02132075]]
после замены:
[[0.76165116 0.23164168 0.73585308]
 [0.13826518 0.18122257 0.1208711 ]
 [0.53406227 0.64195642 0.02132075]]


In [19]:
vect = np.random.randint(0,100,10)
n = 3
largest_val = np.partition(vect, -n)[-n:]
print(f"{vect}\n{largest_val}")

[78 17 38 87  2 85 23 87 64 43]
[85 87 87]


In [20]:
mtrx = np.tile(np.arange(1,6),(5,1))
print(mtrx)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [23]:
mtrx1 = np.random.randint(0,10,(4,4))
mtrx2 = np.random.randint(0,10,(4,4))
prod = mtrx1@mtrx2
diag_elem = np.diagonal(prod)
print(f"{mtrx1}\n\n{mtrx2}\n\n{prod}\n\n{diag_elem}")

[[6 9 9 5]
 [6 0 0 2]
 [5 7 3 2]
 [1 2 5 3]]

[[0 1 2 0]
 [7 9 6 9]
 [6 3 4 5]
 [5 3 4 1]]

[[142 129 122 131]
 [ 10  12  20   2]
 [ 77  83  72  80]
 [ 59  43  46  46]]

[142  12  72  46]


In [24]:
vect = np.arange(20)
split_vect = np.split(vect, 4)
mean_vals = [np.mean(part) for part in split_vect]
print(f"{vect}\n\n{mean_vals}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[2.0, 7.0, 12.0, 17.0]


In [36]:
mtrx = np.random.randint(0,10,(3,3))
print(f"исходная:\n{mtrx}")
max_vals = np.max(mtrx, axis=0)
max_indx = np.argmax(mtrx, axis=0)
mtrx[max_indx, np.arange(mtrx.shape[1])] = 0
print(f"после замены:\n{mtrx}")

исходная:
[[0 7 4]
 [5 1 4]
 [2 6 6]]
после замены:
[[0 0 4]
 [0 1 4]
 [2 6 0]]


In [27]:
mtrx = np.random.randint(0,10,(5,5))
row_sums = np.sum(mtrx, axis=1)
print(row_sums)
max_sum_ind = np.argmax(row_sums)
print(mtrx)
print(max_sum_ind)

[26 30 19 27 24]
[[5 4 5 4 8]
 [7 0 9 5 9]
 [4 0 3 8 4]
 [0 7 5 7 8]
 [8 8 5 1 2]]
1
